const querys = {
    GETPRODUCTS: "SELECT * FROM [ECM].[dbo].[Products] where IsActive = 1",
    GETPRODUCTSBYID: "SELECT * FROM [ECM].[dbo].[Products] WHERE Id=@id",
    GETADMINPRODUCTS:"SELECT * FROM [ECM].[dbo].[Products] where UserId=@userid",
    ADDPRODUCTS:"INSERT INTO [ECM].[dbo].[Products] (UserId,ProductName,ProductPrice,ProductDescription,ImageUrl,ImageKey,Quantity,IsActive) VALUES (@userId,@productName,@productPrice,@productDescription,@imageUrl,@imageKey,@quantity,1);",
    GETPRODUCTBYID: "SELECT * FROM [ECM].[dbo].[Products] WHERE Id= @id",
    UPDATEPRODUCT:"UPDATE [ECM].[dbo].[Products] SET  ProductName=@productName , ProductPrice=@productPrice , ProductDescription=@productDescription ,Quantity=@quantity  WHERE Id = @id and UserId = @userId;",
    UPDATEPRODUCTQUANTITY:"UPDATE [ECM].[dbo].[Products] SET Quantity=@quantity  WHERE Id = @id and UserId = @userId;",
    UPDATEPRODUCTQUANTITYAFTERCANCEL:"UPDATE [ECM].[dbo].[Products] SET Quantity=Quantity+@quantity  WHERE Id = @id and UserId = @userId;",
    DELETEPRODUCTS:"UPDATE [ECM].[dbo].[Products]SET IsActive=0  WHERE Id = @id and UserId = @userId;",
    UPDATEPRODUCTSSTATUS:"UPDATE [ECM].[dbo].[Products] SET IsActive=1  WHERE Id = @id and UserId = @userId;",
    ADDCART:"INSERT INTO [ECM].[dbo].[Cart] (UserId,CartProducts) VALUES (@userId,@cartProducts);",
    UPDATECART:"UPDATE [ECM].[dbo].[Cart] SET CartProducts=@cartProducts WHERE UserId=@userId;",
    CECKUSERINCART:"select * from [ECM].[dbo].[Cart] where UserId=@userId;",
    GETCART:"SELECT * FROM [ECM].[dbo].[Cart] WHERE UserId = @userId",
    DELETECART:"DELETE FROM [ECM].[dbo].[Cart] WHERE ProductId=@productId and UserId=@userId;",
    PLACEORDER:"DELETE FROM [ECM].[dbo].[Cart] WHERE  UserId=@userId;",
    COUNT:"SELECT count(*) as Totalproducts FROM products",
    ADDORDER:"INSERT INTO [ECM].[dbo].[Orders] (UserId,Date,Address,Pincode,ModePayment,CustomerCancel,IsOrderSuccess) VALUES (@userId,@date,@address,@pincode,@modePayment,0,0) SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]",
    GETLASTORDER:"SELECT * FROM [ECM].[dbo].[Orders]",
    ADDORDERPRODUCTS:"INSERT INTO [ECM].[dbo].[OrderProducts] (OrderId,OrderProducts,AdminId,TotalAmount,TotalItemQuantity) VALUES (@orderId,@orderProducts,@adminId,@totalAmount,@totalItemQuantity)",
    GETORDER:"SELECT * FROM [ECM].[dbo].[Orders] WHERE UserId=@userId",
    GETORDERPRODUCTS:"SELECT * FROM [ECM].[dbo].[OrderProducts]",
    GETORDERPRODUCTSBYORDERID:"SELECT * FROM [ECM].[dbo].[OrderProducts] WHERE OrderId=@orderId",
    GETALLORDER:"SELECT * FROM [ECM].[dbo].[Orders]",
    CANCELORDERS:"UPDATE Orders SET CustomerCancel=1 where UserId=@userId and Id=@id",
    GETORDERPRODUCTSADMIN:"SELECT * FROM [ECM].[dbo].[OrderProducts]  WHERE AdminId=@adminId",
    UPDATEORDERS:"UPDATE OrderProducts SET Status=@status,DeliveryDate=@deliveryDate,Message=@message,IsCancel=@isCancel where OrderId=@orderId and AdminId=@adminId",
    CREATETRANS:"INSERT INTO [ECM].[dbo].[Trans] (AdminId,OrderId,TotalAmount,PaymentMode,Message,IsCancel,Date,CustomerCancel) VALUES (@adminId,@orderId,@totalAmount,@paymentMode,@message,@isCancel,@date,0);",
    UPDATETRANS:"UPDATE Trans SET Message=@message,IsCancel=@isCancel,Date=@date where OrderId=@orderId and AdminId=@adminId and Id=@id",
    GETORDERBYID:"SELECT * FROM [ECM].[dbo].[Orders] where Id=@orderId",
    GETORDERPRODUCTSBYID:"SELECT * FROM [ECM].[dbo].[OrderProducts] where OrderId=@orderId and AdminId=@adminId",
    GETTRANS:"SELECT * FROM [ECM].[dbo].[Trans] WHERE AdminId=@adminId",
    GETRANSBYCHECK:"SELECT * FROM [ECM].[dbo].[Trans] WHERE AdminId=@adminId AND OrderId=@orderId",
    UPDATETRANSAFTERCANCEL:"UPDATE TRANS SET CustomerCancel=1 where AdminId=@adminId and OrderId=@orderId",
    GETTOTALORDERSPRODUCTSBYADMIN:"SELECT COUNT(*) AS TOTAL FROM [ECM].[dbo].[OrderProducts] Where AdminId=@adminId;",
    GETTOTALORDERSBYUSER:"SELECT COUNT(*) AS TOTAL FROM [Orders] where UserId=@userId;"
  };


  module.exports=querys